### PR TITLE
Docstrings overhaul and linting

### PR DESCRIPTION
**Pull request by novialriptide**
This is an incomplete pull request. Some values are missing their types since I cannot identify what they actually return. I'll be filling in those missing values soon.

Can I suggest pytmx use the black formatter as well? https://github.com/psf/black

Fixes: https://github.com/bitcraft/pytmx/issues/163

### CODE REVIEW

**Comment by bitcraft** [comment]
i think it already is?  probably with `l=88`.  at some point they changed the default from 88 to 120, and i actually prefer the old default.

**Comment by novialriptide** [comment]
Here's what happens if I run the formatter on pytmx. The black formatter has changed some of its formatting rules recently, so maybe that's why there are a lot of changes.
image

**Comment by bitcraft** [comment]
tbh, i don't think i ran it on the code outside of `pytmx`

**Comment by bitcraft** [comment]
is it convention to duplicate the types in the signature and also the docstrings?  i've left them out of the docstrings intentionally because its redundant.

**Comment by novialriptide** [comment]
> is it convention to duplicate the types in the signature and also the docstrings? i've left them out of the docstrings intentionally because its redundant.

It's what I usually do in my other repositories, but for pytmx's case I think it's better to put the types in the docstrings as well since it's easier to read in the [docs](https://pytmx.readthedocs.io/en/latest/contents.html#module-pytmx.pytmx).

**Comment by novialriptide** [comment]
> i won't ask you to remove the from the docstrings, but the next time i need to change something i will probably remove them. i think the docs problem is related to the templates not reading the function signature and should be fixed there instead of duplicating it.

Got it, I'll start working on the missing types later today.

**Pull request merged**
