### PR TITLE
Add tile type to properties

### PR DESCRIPTION
**Pull request by eruvanos**
image

Adding the 'type' field to the tile properties.

### CODE REVIEW

**Comment by eruvanos** [comment]
Hey, could you please check, should be just a quick look :)

**Comment by bitcraft** [comment]
As `type` is a property, it should be added to the `properties` dictionary.  It is already supported by using TileObject.properties['type'].

**Comment by bitcraft** [comment]
Ok. I see.  You're pr will fix it, but I would prefer to have it implemented as follows:
```python
            p = {k: types[k](v) for k, v in child.items()}
            p.update(parse_properties(child))
```
This will fix `type` and `probability`, as well as any new ones in the future.  Thanks for pointing this issue out!  :D

**Comment by eruvanos** [comment]
Updated the PR. That is much better :)

**Comment by bitcraft** [comment]
Thank you!

**Pull request merged**
