### PR TITLE
Bug fixes, as seen on Discord!

### PR DESCRIPTION
**Pull request by robertpfeiffer**
As promised, bug fixes!

I have a hunch this pull request will re-open #91, but in the current state (before this patch), PyTMX just silently ate my bools and converted them all to `True`, which is significantly worse than not parsing and keeping them as strings `"true"` and `"false"`.

To wit, the code did a roundabout thing to find `bool()`by running `getattr(importlib.import_module('builtins'), 'bool')`, and then `bool()` did the wrong thing because in tiled, `"false"` is falsy, but in Python, it is truthy.

I don't know why you'd want to take that detour instead of `import builtins` or `__builtins__`, so maybe it's a python2 compatibility thing. That said, using `builtins` for custom data types is not extensible anyway. I am *somewhat confident* I am missing and thus breaking @macskay's use case here, but you broke my use case first, so ¯\\\_(ツ)\_/¯

Also, there is the fix for the thing I actually wanted to fix, in 
078dee6ae2a683f540a2154ce9ff214d2c260640.

The files that were causing these problems were made in tiled 1.0.3, out of curiosity I'll clone and compile the newest tiled, but I'd like PyTMX to be backward compatible an any case.

### CODE REVIEW

**Comment by robertpfeiffer** [comment]
I ran `python3 apps/test_pygame.py`, and the version of PyTMX that is currently on PyPI (3.21.6) causes that to crash.

```
INFO:__main__:Testing data/0.9.1/testtrack1.tmx
Traceback (most recent call last):
  File "test_pygame.py", line 240, in <module>
    if not SimpleTest(filename).run():
  File "test_pygame.py", line 141, in __init__
    self.load_map(filename)
  File "test_pygame.py", line 146, in load_map
    self.renderer = TiledRenderer(filename)
  File "test_pygame.py", line 45, in __init__
    tm = load_pygame(filename)
  File "/home/rincewind/.local/lib/python3.6/site-packages/pytmx/util_pygame.py", line 141, in load_pygame
    return pytmx.TiledMap(filename, *args, **kwargs)
  File "/home/rincewind/.local/lib/python3.6/site-packages/pytmx/pytmx.py", line 360, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "/home/rincewind/.local/lib/python3.6/site-packages/pytmx/pytmx.py", line 400, in parse_xml
    self.add_tileset(TiledTileset(self, subnode))
  File "/home/rincewind/.local/lib/python3.6/site-packages/pytmx/pytmx.py", line 845, in __init__
    self.parse_xml(node)
  File "/home/rincewind/.local/lib/python3.6/site-packages/pytmx/pytmx.py", line 894, in parse_xml
    p["path"] = os.path.join(os.path.dirname(source), p["path"])
KeyError: 'path'
```
After my commit 078dee6ae2a683f540a2154ce9ff214d2c260640, test_pygame doesn't crash any more. That was the reason I made this pull request in the first place, because my maps that were made in tiled 1.0.3 did not have that "path" attribute anywhere.

As for backward compatibility of property parsing, version 3.21.6 is already incompatible with older versions of PyTMX in which I used to compare attributes to "true" instead of using them as bools, so code that expected "true" but got `True` was already broken, silently. I had to update my own code to not interpret tile properties as strings. Now it's still incompatible, but at least "correct". This pull request might be a slight improvement over the status quo, not the be-all-end-all.

**Comment by robertpfeiffer** [comment]
I merged the lastest commits from master
test_properties_are_converted_to_builtin_types still fails on current master

**Comment by robertpfeiffer** [comment]
this is also related to #115

**Comment by robertpfeiffer** [comment]
It's been a year.

**Comment by bitcraft** [comment]
I think this was fixed by another commit (multiple issues were raised around this boolean thing, and I just fixed one of them).  Can you verify if this solves your problem?

**Comment by bitcraft** [comment]
@robertpfeiffer ^^^

**Comment by robertpfeiffer** [comment]
I merged in your latest code and ran my test cases again. Looks good. The only thing left in this PR is now the test case and a more explicit log message.

**Comment by bitcraft** [comment]
cool looks good to me, thank you for these changes.

**Pull request merged**
